name: Walling
favicon: null
layout_spectrum: 0.08247
typography_spectrum: 0.9556419034488499
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#737c5f'
    - '#f2eeeb'
    - '#272123'
    - '#b7aebf'
    - '#d28d6c'
  brandStrength: 0
  lightness: 0.9696786077693105
  saturation: 0.5604743412695825
  rhythmicContrast: 0.27342150267213583
purpose: []
